CREATE AN ARRAY OF 10 ZEROS

In [1]:
import numpy as np

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

CREATE AN ARRAY OF 10 ONES

In [2]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

CREATE AN ARRAY OF 10 FIVES

In [3]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [5]:
np.arange(10, 51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.random.rand(1)

array([0.81875331])

In [9]:
np.random.rand(25).reshape(5,5)

array([[0.3725217 , 0.60185734, 0.97303344, 0.60657078, 0.09720153],
       [0.31571049, 0.46763435, 0.11959198, 0.37209815, 0.46610324],
       [0.6252661 , 0.69934665, 0.14240788, 0.6145153 , 0.35016808],
       [0.85552377, 0.29206296, 0.87443278, 0.4766489 , 0.26847149],
       [0.40488873, 0.14932464, 0.86851019, 0.16681624, 0.65291634]])

In [10]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [11]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
arr[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
arr[3,4]

20

In [15]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [16]:
arr[4:5]

array([[21, 22, 23, 24, 25]])

In [17]:
arr[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Get the sum of arr

In [18]:
np.sum(arr)

325

In [19]:
np.std(arr)

7.211102550927978

axix=1 for Rows and axis=0 for column

In [20]:
np.sum(arr,axis=0)

array([55, 60, 65, 70, 75])

In [21]:
np.sum(arr,axis=1)

array([ 15,  40,  65,  90, 115])

Assignment

In [22]:
oneD=np.arange(0,12)
oneD

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
twoD=np.arange(0,12).reshape(3,4)
twoD

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
threeD=np.arange(0,12).reshape(3,2,2)
threeD

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [25]:
oneD.dtype
twoD.dtype
threeD.dtype

dtype('int32')

In [26]:
oneD.shape

(12,)

In [27]:
twoD.shape

(3, 4)

In [28]:
threeD.shape

(3, 2, 2)

In [29]:
oneD.ndim

1

In [30]:
twoD.ndim

2

In [31]:
threeD.ndim

3

In [32]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros(12).reshape(3,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
math=np.random.randint(0,100,20)
math

array([93, 61, 49, 76, 76, 16, 49, 83, 86, 15, 37, 69,  9, 53, 53, 32,  1,
       77, 58, 61])

In [35]:
sort=np.sort(math)
sort

array([ 1,  9, 15, 16, 32, 37, 49, 49, 53, 53, 58, 61, 61, 69, 76, 76, 77,
       83, 86, 93])

In [36]:
np.flip(sort)

array([93, 86, 83, 77, 76, 76, 69, 61, 61, 58, 53, 53, 49, 49, 37, 32, 16,
       15,  9,  1])

In [37]:
copy1=np.copy(sort)
copy1

array([ 1,  9, 15, 16, 32, 37, 49, 49, 53, 53, 58, 61, 61, 69, 76, 76, 77,
       83, 86, 93])

In [38]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.eye(5).reshape(25,)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [40]:
one=np.arange(1,10).reshape(3,3)
np.append(one,[[10,11,12]],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
np.vstack((one,[10,11,12]))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
np.hstack((one,[[4],[6],[9]]))

array([[1, 2, 3, 4],
       [4, 5, 6, 6],
       [7, 8, 9, 9]])

In [43]:
np.hsplit(one,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [44]:
np.vsplit(one,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [45]:
np.eye(4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [46]:
Q13=np.random.uniform(0,9,10)
Q13

array([5.88926477, 1.5276017 , 6.99036189, 2.49478174, 2.35722605,
       3.61052685, 7.22338703, 5.61352395, 1.03586506, 1.96571276])

In [47]:
np.ceil(Q13)

array([6., 2., 7., 3., 3., 4., 8., 6., 2., 2.])

In [48]:
np.floor(Q13)

array([5., 1., 6., 2., 2., 3., 7., 5., 1., 1.])

In [49]:
np.round(Q13,decimals=2)

array([5.89, 1.53, 6.99, 2.49, 2.36, 3.61, 7.22, 5.61, 1.04, 1.97])

In [50]:
Q14=np.arange(0,25).reshape(5,5)
Q14

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
Q14.min(axis=0)

array([0, 1, 2, 3, 4])

In [52]:
Q14.max(axis=0)

array([20, 21, 22, 23, 24])

In [53]:
Q14.var(axis=0)

array([50., 50., 50., 50., 50.])

In [54]:
Q14.std(axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [55]:
Q15 = np.full((10,), 'NaN')
Q15[5] = 200
print(Q15)

['NaN' 'NaN' 'NaN' 'NaN' 'NaN' '200' 'NaN' 'NaN' 'NaN' 'NaN']


In [56]:
import numpy as np
Q16=np.arange(100,151)
Q16

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [57]:
np.flip(Q16)

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [58]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
Q19=[1,0,2,0,0,4,0,8]
np.nonzero(Q19)

(array([0, 2, 5, 7], dtype=int64),)

In [60]:
Q20=np.ones((10,10))
Q20[1:9,1:9]=0
Q20

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [61]:
Q21=np.ones((8,8))
Q21[::2,::2]=0
Q21[1::2,1::2]=0
Q21

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [62]:
mat1=np.random.randint(0,10,9).reshape(3,3)
mat2=np.random.randint(0,10,9).reshape(3,3)
mat1

array([[2, 2, 9],
       [3, 7, 3],
       [1, 8, 0]])

In [63]:
mat2

array([[8, 1, 8],
       [0, 7, 5],
       [0, 3, 2]])

In [64]:
sum=mat1+mat2
sum

array([[10,  3, 17],
       [ 3, 14,  8],
       [ 1, 11,  2]])

In [65]:
mul=mat1@mat2
mul

array([[16, 43, 44],
       [24, 61, 65],
       [ 8, 57, 48]])

In [66]:
sub=mat1-mat2
sub

array([[-6,  1,  1],
       [ 3,  0, -2],
       [ 1,  5, -2]])